package prolog;

import jp.ac.kobe_u.cs.prolog.lang.*;
import jp.ac.kobe_u.cs.prolog.builtin.*;
/*
 This file is generated by Prolog Cafe.
 PLEASE DO NOT EDIT!
*/
/**
 <code>foldl/4</code> defined in functional.pro<br>
 @author Mutsunori Banbara (banbara@kobe-u.ac.jp)
 @author Naoyuki Tamura (tamura@kobe-u.ac.jp)
 @version 1.0
*/
public class PRED_foldl_4 extends Predicate {
    static SymbolTerm s1 = SymbolTerm.makeSymbol("[]");
    static Predicate _fail_0 = new PRED_fail_0();
    static Predicate _foldl_4_var = new PRED_foldl_4_var();
    static Predicate _foldl_4_var_1 = new PRED_foldl_4_var_1();
    static Predicate _foldl_4_1 = new PRED_foldl_4_1();
    static Predicate _foldl_4_2 = new PRED_foldl_4_2();

    public Term arg1, arg2, arg3, arg4;

    public PRED_foldl_4(Term a1, Term a2, Term a3, Term a4, Predicate cont) {
        arg1 = a1;
        arg2 = a2;
        arg3 = a3;
        arg4 = a4;
        this.cont = cont;
    }

    public PRED_foldl_4(){}

    public void setArgument(Term[] args, Predicate cont) {
        arg1 = args[0];
        arg2 = args[1];
        arg3 = args[2];
        arg4 = args[3];
        this.cont = cont;
    }

    public int arity() { return 4; }

    public String toString() {
        return "foldl(" + arg1 + "," + arg2 + "," + arg3 + "," + arg4 + ")";
    }

    public Predicate exec(Prolog engine) {
        engine.aregs[1] = arg1;
        engine.aregs[2] = arg2;
        engine.aregs[3] = arg3;
        engine.aregs[4] = arg4;
        engine.cont = cont;
        engine.setB0();
        return engine.switch_on_term(_foldl_4_var, _fail_0, _fail_0, _foldl_4_1, _fail_0, _foldl_4_2);
    }
}

class PRED_foldl_4_var extends PRED_foldl_4 {
    public Predicate exec(Prolog engine) {
        return engine.jtry(_foldl_4_1, _foldl_4_var_1);
    }
}

class PRED_foldl_4_var_1 extends PRED_foldl_4 {
    public Predicate exec(Prolog engine) {
        return engine.trust(_foldl_4_2);
    }
}

class PRED_foldl_4_1 extends PRED_foldl_4 {
    public Predicate exec(Prolog engine) {
    // foldl([],A,B,B):-true
        Term a1, a2, a3, a4;
        Predicate cont;
        a1 = engine.aregs[1];
        a2 = engine.aregs[2];
        a3 = engine.aregs[3];
        a4 = engine.aregs[4];
        cont = engine.cont;
    // foldl([],A,B,B):-[]
        a1 = a1.dereference();
        if (a1.isSymbol()){
            if (! a1.equals(s1))
                return engine.fail();
        } else if (a1.isVariable()){
            ((VariableTerm) a1).bind(s1, engine.trail);
        } else {
            return engine.fail();
        }
        if (! a3.unify(a4, engine.trail))
            return engine.fail();
        return cont;
    }
}

class PRED_foldl_4_2 extends PRED_foldl_4 {
    public Predicate exec(Prolog engine) {
    // foldl([A|B],C,D,E):-call(C,D,A,F),foldl(B,C,F,E)
        Term a1, a2, a3, a4, a5, a6, a7;
        Predicate p1;
        Predicate cont;
        a1 = engine.aregs[1];
        a2 = engine.aregs[2];
        a3 = engine.aregs[3];
        a4 = engine.aregs[4];
        cont = engine.cont;
    // foldl([A|B],C,D,E):-[call(C,D,A,F),foldl(B,C,F,E)]
        a1 = a1.dereference();
        if (a1.isList()){
            Term[] args = {((ListTerm)a1).car(), ((ListTerm)a1).cdr()};
            a5 = args[0];
            a6 = args[1];
        } else if (a1.isVariable()){
            a5 = new VariableTerm(engine);
            a6 = new VariableTerm(engine);
            ((VariableTerm) a1).bind(new ListTerm(a5, a6), engine.trail);
        } else {
            return engine.fail();
        }
        a7 = new VariableTerm(engine);
        p1 = new PRED_foldl_4(a6, a2, a7, a4, cont);
        return new PRED_call_4(a2, a3, a5, a7, p1);
    }
}
