package prolog;

import jp.ac.kobe_u.cs.prolog.lang.*;
import jp.ac.kobe_u.cs.prolog.builtin.*;
/*
 This file is generated by Prolog Cafe.
 PLEASE DO NOT EDIT!
*/
/**
 <code>append/2</code> defined in plcafe_defs.pro<br>
 @author Mutsunori Banbara (banbara@kobe-u.ac.jp)
 @author Naoyuki Tamura (tamura@kobe-u.ac.jp)
 @version 1.0
*/
public class PRED_append_2 extends Predicate {
    static SymbolTerm s1 = SymbolTerm.makeSymbol("[]");
    static Predicate _append_2_top = new PRED_append_2_top();
    static Predicate _fail_0 = new PRED_fail_0();
    static Predicate _append_2_var = new PRED_append_2_var();
    static Predicate _append_2_var_1 = new PRED_append_2_var_1();
    static Predicate _append_2_1 = new PRED_append_2_1();
    static Predicate _append_2_2 = new PRED_append_2_2();

    public Term arg1, arg2;

    public PRED_append_2(Term a1, Term a2, Predicate cont) {
        arg1 = a1;
        arg2 = a2;
        this.cont = cont;
    }

    public PRED_append_2(){}

    public void setArgument(Term[] args, Predicate cont) {
        arg1 = args[0];
        arg2 = args[1];
        this.cont = cont;
    }

    public int arity() { return 2; }

    public String toString() {
        return "append(" + arg1 + "," + arg2 + ")";
    }

    public Predicate exec(Prolog engine) {
        engine.aregs[1] = arg1;
        engine.aregs[2] = arg2;
        engine.cont = cont;
        return _append_2_top;
    }
}

class PRED_append_2_top extends PRED_append_2 {
    public Predicate exec(Prolog engine) {
        engine.setB0();
        return engine.switch_on_term(_append_2_var, _fail_0, _fail_0, _append_2_1, _fail_0, _append_2_2);
    }
}

class PRED_append_2_var extends PRED_append_2 {
    public Predicate exec(Prolog engine) {
        return engine.jtry(_append_2_1, _append_2_var_1);
    }
}

class PRED_append_2_var_1 extends PRED_append_2 {
    public Predicate exec(Prolog engine) {
        return engine.trust(_append_2_2);
    }
}

class PRED_append_2_1 extends PRED_append_2 {
    public Predicate exec(Prolog engine) {
    // append([],[]):-true
        Term a1, a2;
        Predicate cont;
        a1 = engine.aregs[1];
        a2 = engine.aregs[2];
        cont = engine.cont;
    // append([],[]):-[]
        a1 = a1.dereference();
        if (a1.isSymbol()){
            if (! a1.equals(s1))
                return engine.fail();
        } else if (a1.isVariable()){
            ((VariableTerm) a1).bind(s1, engine.trail);
        } else {
            return engine.fail();
        }
        a2 = a2.dereference();
        if (a2.isSymbol()){
            if (! a2.equals(s1))
                return engine.fail();
        } else if (a2.isVariable()){
            ((VariableTerm) a2).bind(s1, engine.trail);
        } else {
            return engine.fail();
        }
        return cont;
    }
}

class PRED_append_2_2 extends PRED_append_2 {
    public Predicate exec(Prolog engine) {
    // append([A|B],C):-append(B,D),append(A,D,C)
        Term a1, a2, a3, a4, a5;
        Predicate p1;
        Predicate cont;
        a1 = engine.aregs[1];
        a2 = engine.aregs[2];
        cont = engine.cont;
    // append([A|B],C):-[append(B,D),append(A,D,C)]
        a1 = a1.dereference();
        if (a1.isList()){
            Term[] args = {((ListTerm)a1).car(), ((ListTerm)a1).cdr()};
            a3 = args[0];
            a4 = args[1];
        } else if (a1.isVariable()){
            a3 = new VariableTerm(engine);
            a4 = new VariableTerm(engine);
            ((VariableTerm) a1).bind(new ListTerm(a3, a4), engine.trail);
        } else {
            return engine.fail();
        }
        a5 = new VariableTerm(engine);
        p1 = new PRED_append_3(a3, a5, a2, cont);
        engine.aregs[1] = a4;
        engine.aregs[2] = a5;
        engine.cont = p1;
        return _append_2_top;
    }
}
