package prolog;

import jp.ac.kobe_u.cs.prolog.lang.*;
import jp.ac.kobe_u.cs.prolog.builtin.*;
/*
 This file is generated by Prolog Cafe.
 PLEASE DO NOT EDIT!
*/
/**
 <code>attr_statistics/4</code> defined in rule_initialize.pro<br>
 @author Mutsunori Banbara (banbara@kobe-u.ac.jp)
 @author Naoyuki Tamura (tamura@kobe-u.ac.jp)
 @version 1.0
*/
public class PRED_attr_statistics_4 extends Predicate {
    static SymbolTerm s1 = SymbolTerm.makeSymbol("first");
    static SymbolTerm s2 = SymbolTerm.makeSymbol("second");

    public Term arg1, arg2, arg3, arg4;

    public PRED_attr_statistics_4(Term a1, Term a2, Term a3, Term a4, Predicate cont) {
        arg1 = a1;
        arg2 = a2;
        arg3 = a3;
        arg4 = a4;
        this.cont = cont;
    }

    public PRED_attr_statistics_4(){}

    public void setArgument(Term[] args, Predicate cont) {
        arg1 = args[0];
        arg2 = args[1];
        arg3 = args[2];
        arg4 = args[3];
        this.cont = cont;
    }

    public int arity() { return 4; }

    public String toString() {
        return "attr_statistics(" + arg1 + "," + arg2 + "," + arg3 + "," + arg4 + ")";
    }

    public Predicate exec(Prolog engine) {
    // attr_statistics(A,B,C,D):-transpose_attrs(A,E),map_fast(E,first,D),map_fast(E,second,F),map_fast(F,B,C)
        engine.setB0();
        Term a1, a2, a3, a4, a5, a6;
        Predicate p1, p2, p3;
        a1 = arg1;
        a2 = arg2;
        a3 = arg3;
        a4 = arg4;
    // attr_statistics(A,B,C,D):-[transpose_attrs(A,E),map_fast(E,first,D),map_fast(E,second,F),map_fast(F,B,C)]
        a5 = new VariableTerm(engine);
        a6 = new VariableTerm(engine);
        p1 = new PRED_map_fast_3(a6, a2, a3, cont);
        p2 = new PRED_map_fast_3(a5, s2, a6, p1);
        p3 = new PRED_map_fast_3(a5, s1, a4, p2);
        return new PRED_transpose_attrs_2(a1, a5, p3);
    }
}
