package prolog;

import jp.ac.kobe_u.cs.prolog.lang.*;
import jp.ac.kobe_u.cs.prolog.builtin.*;
/*
 This file is generated by Prolog Cafe.
 PLEASE DO NOT EDIT!
*/
/**
 <code>grab_assocs_and_map/5</code> defined in attributes.pro<br>
 @author Mutsunori Banbara (banbara@kobe-u.ac.jp)
 @author Naoyuki Tamura (tamura@kobe-u.ac.jp)
 @version 1.0
*/
public class PRED_grab_assocs_and_map_5 extends Predicate {
    static SymbolTerm s1 = SymbolTerm.makeSymbol("[]");
    static Predicate _fail_0 = new PRED_fail_0();
    static Predicate _grab_assocs_and_map_5_var = new PRED_grab_assocs_and_map_5_var();
    static Predicate _grab_assocs_and_map_5_var_1 = new PRED_grab_assocs_and_map_5_var_1();
    static Predicate _grab_assocs_and_map_5_1 = new PRED_grab_assocs_and_map_5_1();
    static Predicate _grab_assocs_and_map_5_2 = new PRED_grab_assocs_and_map_5_2();

    public Term arg1, arg2, arg3, arg4, arg5;

    public PRED_grab_assocs_and_map_5(Term a1, Term a2, Term a3, Term a4, Term a5, Predicate cont) {
        arg1 = a1;
        arg2 = a2;
        arg3 = a3;
        arg4 = a4;
        arg5 = a5;
        this.cont = cont;
    }

    public PRED_grab_assocs_and_map_5(){}

    public void setArgument(Term[] args, Predicate cont) {
        arg1 = args[0];
        arg2 = args[1];
        arg3 = args[2];
        arg4 = args[3];
        arg5 = args[4];
        this.cont = cont;
    }

    public int arity() { return 5; }

    public String toString() {
        return "grab_assocs_and_map(" + arg1 + "," + arg2 + "," + arg3 + "," + arg4 + "," + arg5 + ")";
    }

    public Predicate exec(Prolog engine) {
        engine.aregs[1] = arg1;
        engine.aregs[2] = arg2;
        engine.aregs[3] = arg3;
        engine.aregs[4] = arg4;
        engine.aregs[5] = arg5;
        engine.cont = cont;
        engine.setB0();
        return engine.switch_on_term(_grab_assocs_and_map_5_var, _fail_0, _fail_0, _grab_assocs_and_map_5_1, _fail_0, _grab_assocs_and_map_5_2);
    }
}

class PRED_grab_assocs_and_map_5_var extends PRED_grab_assocs_and_map_5 {
    public Predicate exec(Prolog engine) {
        return engine.jtry(_grab_assocs_and_map_5_1, _grab_assocs_and_map_5_var_1);
    }
}

class PRED_grab_assocs_and_map_5_var_1 extends PRED_grab_assocs_and_map_5 {
    public Predicate exec(Prolog engine) {
        return engine.trust(_grab_assocs_and_map_5_2);
    }
}

class PRED_grab_assocs_and_map_5_1 extends PRED_grab_assocs_and_map_5 {
    public Predicate exec(Prolog engine) {
    // grab_assocs_and_map([],A,B,C,[]):-true
        Term a1, a2, a3, a4, a5;
        Predicate cont;
        a1 = engine.aregs[1];
        a2 = engine.aregs[2];
        a3 = engine.aregs[3];
        a4 = engine.aregs[4];
        a5 = engine.aregs[5];
        cont = engine.cont;
    // grab_assocs_and_map([],A,B,C,[]):-[]
        a1 = a1.dereference();
        if (a1.isSymbol()){
            if (! a1.equals(s1))
                return engine.fail();
        } else if (a1.isVariable()){
            ((VariableTerm) a1).bind(s1, engine.trail);
        } else {
            return engine.fail();
        }
        a5 = a5.dereference();
        if (a5.isSymbol()){
            if (! a5.equals(s1))
                return engine.fail();
        } else if (a5.isVariable()){
            ((VariableTerm) a5).bind(s1, engine.trail);
        } else {
            return engine.fail();
        }
        return cont;
    }
}

class PRED_grab_assocs_and_map_5_2 extends PRED_grab_assocs_and_map_5 {
    public Predicate exec(Prolog engine) {
    // grab_assocs_and_map([A|B],C,D,E,F):-map_maybe_assoc(C,A,G),'$dummy_13_attributes.pro'(G,D,C,H,B,I,F,E,J,A)
        Term a1, a2, a3, a4, a5, a6, a7, a8;
        Predicate p1;
        Predicate cont;
        a1 = engine.aregs[1];
        a2 = engine.aregs[2];
        a3 = engine.aregs[3];
        a4 = engine.aregs[4];
        a5 = engine.aregs[5];
        cont = engine.cont;
    // grab_assocs_and_map([A|B],C,D,E,F):-[map_maybe_assoc(C,A,G),'$dummy_13_attributes.pro'(G,D,C,H,B,I,F,E,J,A)]
        a1 = a1.dereference();
        if (a1.isList()){
            Term[] args = {((ListTerm)a1).car(), ((ListTerm)a1).cdr()};
            a6 = args[0];
            a7 = args[1];
        } else if (a1.isVariable()){
            a6 = new VariableTerm(engine);
            a7 = new VariableTerm(engine);
            ((VariableTerm) a1).bind(new ListTerm(a6, a7), engine.trail);
        } else {
            return engine.fail();
        }
        a8 = new VariableTerm(engine);
        p1 = new PRED_$dummy_13_attributes$002Epro_10(a8, a3, a2, new VariableTerm(engine), a7, new VariableTerm(engine), a5, a4, new VariableTerm(engine), a6, cont);
        return new PRED_map_maybe_assoc_3(a2, a6, a8, p1);
    }
}
