package prolog;

import jp.ac.kobe_u.cs.prolog.lang.*;
import jp.ac.kobe_u.cs.prolog.builtin.*;
/*
 This file is generated by Prolog Cafe.
 PLEASE DO NOT EDIT!
*/
/**
 <code>density_helper/2</code> defined in attributes.pro<br>
 @author Mutsunori Banbara (banbara@kobe-u.ac.jp)
 @author Naoyuki Tamura (tamura@kobe-u.ac.jp)
 @version 1.0
*/
public class PRED_density_helper_2 extends Predicate {
    static SymbolTerm s1 = SymbolTerm.makeSymbol("[]");
    static IntegerTerm si2 = new IntegerTerm(0);
    static SymbolTerm s3 = SymbolTerm.makeSymbol("t", 2);
    static Predicate _density_helper_2_top = new PRED_density_helper_2_top();
    static Predicate _fail_0 = new PRED_fail_0();
    static Predicate _density_helper_2_var = new PRED_density_helper_2_var();
    static Predicate _density_helper_2_var_1 = new PRED_density_helper_2_var_1();
    static Predicate _density_helper_2_1 = new PRED_density_helper_2_1();
    static Predicate _density_helper_2_2 = new PRED_density_helper_2_2();

    public Term arg1, arg2;

    public PRED_density_helper_2(Term a1, Term a2, Predicate cont) {
        arg1 = a1;
        arg2 = a2;
        this.cont = cont;
    }

    public PRED_density_helper_2(){}

    public void setArgument(Term[] args, Predicate cont) {
        arg1 = args[0];
        arg2 = args[1];
        this.cont = cont;
    }

    public int arity() { return 2; }

    public String toString() {
        return "density_helper(" + arg1 + "," + arg2 + ")";
    }

    public Predicate exec(Prolog engine) {
        engine.aregs[1] = arg1;
        engine.aregs[2] = arg2;
        engine.cont = cont;
        return _density_helper_2_top;
    }
}

class PRED_density_helper_2_top extends PRED_density_helper_2 {
    public Predicate exec(Prolog engine) {
        engine.setB0();
        return engine.switch_on_term(_density_helper_2_var, _fail_0, _fail_0, _density_helper_2_1, _fail_0, _density_helper_2_2);
    }
}

class PRED_density_helper_2_var extends PRED_density_helper_2 {
    public Predicate exec(Prolog engine) {
        return engine.jtry(_density_helper_2_1, _density_helper_2_var_1);
    }
}

class PRED_density_helper_2_var_1 extends PRED_density_helper_2 {
    public Predicate exec(Prolog engine) {
        return engine.trust(_density_helper_2_2);
    }
}

class PRED_density_helper_2_1 extends PRED_density_helper_2 {
    public Predicate exec(Prolog engine) {
    // density_helper([],0):-true
        Term a1, a2;
        Predicate cont;
        a1 = engine.aregs[1];
        a2 = engine.aregs[2];
        cont = engine.cont;
    // density_helper([],0):-[]
        a1 = a1.dereference();
        if (a1.isSymbol()){
            if (! a1.equals(s1))
                return engine.fail();
        } else if (a1.isVariable()){
            ((VariableTerm) a1).bind(s1, engine.trail);
        } else {
            return engine.fail();
        }
        a2 = a2.dereference();
        if (a2.isInteger()){
            if (((IntegerTerm) a2).intValue() != 0)
                return engine.fail();
        } else if (a2.isVariable()){
            ((VariableTerm) a2).bind(si2, engine.trail);
        } else {
            return engine.fail();
        }
        return cont;
    }
}

class PRED_density_helper_2_2 extends PRED_density_helper_2 {
    public Predicate exec(Prolog engine) {
    // density_helper([t(A,B)|C],D):-density_helper(C,E),'$dummy_16_attributes.pro'(F,A,B),D is F+E
        Term a1, a2, a3, a4, a5, a6, a7, a8;
        Predicate p1, p2;
        Predicate cont;
        a1 = engine.aregs[1];
        a2 = engine.aregs[2];
        cont = engine.cont;
    // density_helper([t(A,B)|C],D):-[density_helper(C,E),'$dummy_16_attributes.pro'(F,A,B),'$plus'(F,E,D)]
        a1 = a1.dereference();
        if (a1.isList()){
            Term[] args = {((ListTerm)a1).car(), ((ListTerm)a1).cdr()};
            a3 = args[0];
            a4 = args[1];
        } else if (a1.isVariable()){
            a3 = new VariableTerm(engine);
            a4 = new VariableTerm(engine);
            ((VariableTerm) a1).bind(new ListTerm(a3, a4), engine.trail);
        } else {
            return engine.fail();
        }
        a3 = a3.dereference();
        if (a3.isStructure()){
            if (! s3.equals(((StructureTerm)a3).functor()))
                return engine.fail();
            Term[] args = ((StructureTerm)a3).args();
            a5 = args[0];
            a6 = args[1];
        } else if (a3.isVariable()){
            a5 = new VariableTerm(engine);
            a6 = new VariableTerm(engine);
            Term[] args = {a5, a6};
            ((VariableTerm) a3).bind(new StructureTerm(s3, args), engine.trail);
        } else {
            return engine.fail();
        }
        a7 = new VariableTerm(engine);
        a8 = new VariableTerm(engine);
        p1 = new PRED_$plus_3(a8, a7, a2, cont);
        p2 = new PRED_$dummy_16_attributes$002Epro_3(a8, a5, a6, p1);
        engine.aregs[1] = a4;
        engine.aregs[2] = a7;
        engine.cont = p2;
        return _density_helper_2_top;
    }
}
