import jp.ac.kobe_u.cs.prolog.lang.*;
import jp.ac.kobe_u.cs.prolog.builtin.*;
/*
 This file is generated by Prolog Cafe.
 PLEASE DO NOT EDIT!
*/
/**
 <code>retract_medians/0</code> defined in rule_database.pro<br>
 @author Mutsunori Banbara (banbara@kobe-u.ac.jp)
 @author Naoyuki Tamura (tamura@kobe-u.ac.jp)
 @version 1.0
*/
public class PRED_retract_medians_0 extends Predicate {
    static SymbolTerm s1 = SymbolTerm.makeSymbol("attr_median_diff", 2);

    public PRED_retract_medians_0(Predicate cont) {
        this.cont = cont;
    }

    public PRED_retract_medians_0(){}

    public void setArgument(Term[] args, Predicate cont) {
        this.cont = cont;
    }

    public int arity() { return 0; }

    public String toString() {
        return "retract_medians";
    }

    public Predicate exec(Prolog engine) {
    // retract_medians:-retractall_nonvar(attr_median_diff(A,B))
        engine.setB0();
        Term a1;
    // retract_medians:-[retractall_nonvar(attr_median_diff(A,B))]
        Term[] y1 = {new VariableTerm(engine), new VariableTerm(engine)};
        a1 = new StructureTerm(s1, y1);
        return new PRED_retractall_nonvar_1(a1, cont);
    }
}
