package prolog;

import jp.ac.kobe_u.cs.prolog.lang.*;
import jp.ac.kobe_u.cs.prolog.builtin.*;
/*
 This file is generated by Prolog Cafe.
 PLEASE DO NOT EDIT!
*/
/**
 <code>test_onset_list_helper/0</code> defined in longuet_higgins.pro<br>
 @author Mutsunori Banbara (banbara@kobe-u.ac.jp)
 @author Naoyuki Tamura (tamura@kobe-u.ac.jp)
 @version 1.0
*/
public class PRED_test_onset_list_helper_0 extends Predicate {
    static IntegerTerm si1 = new IntegerTerm(120);
    static IntegerTerm si2 = new IntegerTerm(240);
    static SymbolTerm s3 = SymbolTerm.makeSymbol("[]");
    static ListTerm s4 = new ListTerm(si2, s3);
    static ListTerm s5 = new ListTerm(si1, s4);
    static IntegerTerm si6 = new IntegerTerm(0);
    static ListTerm s7 = new ListTerm(si6, s3);
    static IntegerTerm si8 = new IntegerTerm(360);
    static ListTerm s9 = new ListTerm(si8, s3);
    static ListTerm s10 = new ListTerm(si1, s9);
    static ListTerm s11 = new ListTerm(si6, s10);
    static IntegerTerm si12 = new IntegerTerm(2);
    static IntegerTerm si13 = new IntegerTerm(3);
    static IntegerTerm si14 = new IntegerTerm(4);
    static ListTerm s15 = new ListTerm(si14, s3);
    static ListTerm s16 = new ListTerm(si13, s15);
    static ListTerm s17 = new ListTerm(si12, s16);
    static IntegerTerm si18 = new IntegerTerm(1);
    static ListTerm s19 = new ListTerm(si18, s3);
    static IntegerTerm si20 = new IntegerTerm(6);
    static IntegerTerm si21 = new IntegerTerm(10);
    static ListTerm s22 = new ListTerm(si21, s3);
    static ListTerm s23 = new ListTerm(si20, s22);
    static ListTerm s24 = new ListTerm(si13, s23);
    static ListTerm s25 = new ListTerm(si18, s24);

    public PRED_test_onset_list_helper_0(Predicate cont) {
        this.cont = cont;
    }

    public PRED_test_onset_list_helper_0(){}

    public void setArgument(Term[] args, Predicate cont) {
        this.cont = cont;
    }

    public int arity() { return 0; }

    public String toString() {
        return "test_onset_list_helper";
    }

    public Predicate exec(Prolog engine) {
    // test_onset_list_helper:-onset_list_helper([120,240],[0],[0,120,360]),onset_list_helper([2,3,4],[1],[1,3,6,10])
        engine.setB0();
        Predicate p1;
    // test_onset_list_helper:-[onset_list_helper([120,240],[0],[0,120,360]),onset_list_helper([2,3,4],[1],[1,3,6,10])]
        p1 = new PRED_onset_list_helper_3(s17, s19, s25, cont);
        return new PRED_onset_list_helper_3(s5, s7, s11, p1);
    }
}
