package prolog;

import jp.ac.kobe_u.cs.prolog.lang.*;
import jp.ac.kobe_u.cs.prolog.builtin.*;
/*
 This file is generated by Prolog Cafe.
 PLEASE DO NOT EDIT!
*/
/**
 <code>expand_fully/2</code> defined in random_helpers.pro<br>
 @author Mutsunori Banbara (banbara@kobe-u.ac.jp)
 @author Naoyuki Tamura (tamura@kobe-u.ac.jp)
 @version 1.0
*/
public class PRED_expand_fully_2 extends Predicate {
    static SymbolTerm s1 = SymbolTerm.makeSymbol("[]");
    static Predicate _expand_fully_2_var = new PRED_expand_fully_2_var();
    static Predicate _expand_fully_2_var_1 = new PRED_expand_fully_2_var_1();
    static Predicate _expand_fully_2_1 = new PRED_expand_fully_2_1();
    static Predicate _expand_fully_2_2 = new PRED_expand_fully_2_2();

    public Term arg1, arg2;

    public PRED_expand_fully_2(Term a1, Term a2, Predicate cont) {
        arg1 = a1;
        arg2 = a2;
        this.cont = cont;
    }

    public PRED_expand_fully_2(){}

    public void setArgument(Term[] args, Predicate cont) {
        arg1 = args[0];
        arg2 = args[1];
        this.cont = cont;
    }

    public int arity() { return 2; }

    public String toString() {
        return "expand_fully(" + arg1 + "," + arg2 + ")";
    }

    public Predicate exec(Prolog engine) {
        engine.aregs[1] = arg1;
        engine.aregs[2] = arg2;
        engine.cont = cont;
        engine.setB0();
        return engine.switch_on_term(_expand_fully_2_var, _expand_fully_2_2, _expand_fully_2_2, _expand_fully_2_var, _expand_fully_2_2, _expand_fully_2_2);
    }
}

class PRED_expand_fully_2_var extends PRED_expand_fully_2 {
    public Predicate exec(Prolog engine) {
        return engine.jtry(_expand_fully_2_1, _expand_fully_2_var_1);
    }
}

class PRED_expand_fully_2_var_1 extends PRED_expand_fully_2 {
    public Predicate exec(Prolog engine) {
        return engine.trust(_expand_fully_2_2);
    }
}

class PRED_expand_fully_2_1 extends PRED_expand_fully_2 {
    public Predicate exec(Prolog engine) {
    // expand_fully([],[]):-true
        Term a1, a2;
        Predicate cont;
        a1 = engine.aregs[1];
        a2 = engine.aregs[2];
        cont = engine.cont;
    // expand_fully([],[]):-[]
        a1 = a1.dereference();
        if (a1.isSymbol()){
            if (! a1.equals(s1))
                return engine.fail();
        } else if (a1.isVariable()){
            ((VariableTerm) a1).bind(s1, engine.trail);
        } else {
            return engine.fail();
        }
        a2 = a2.dereference();
        if (a2.isSymbol()){
            if (! a2.equals(s1))
                return engine.fail();
        } else if (a2.isVariable()){
            ((VariableTerm) a2).bind(s1, engine.trail);
        } else {
            return engine.fail();
        }
        return cont;
    }
}

class PRED_expand_fully_2_2 extends PRED_expand_fully_2 {
    public Predicate exec(Prolog engine) {
    // expand_fully(A,[B|C]):-A=[D|E],'$dummy_0_random_helpers.pro'(F,C,G,H,I,B,J,D,E,A)
        Term a1, a2, a3, a4, a5, a6, a7;
        Predicate cont;
        a1 = engine.aregs[1];
        a2 = engine.aregs[2];
        cont = engine.cont;
    // expand_fully(A,[B|C]):-['$unify'(A,[D|E]),'$dummy_0_random_helpers.pro'(F,C,G,H,I,B,J,D,E,A)]
        a2 = a2.dereference();
        if (a2.isList()){
            Term[] args = {((ListTerm)a2).car(), ((ListTerm)a2).cdr()};
            a3 = args[0];
            a4 = args[1];
        } else if (a2.isVariable()){
            a3 = new VariableTerm(engine);
            a4 = new VariableTerm(engine);
            ((VariableTerm) a2).bind(new ListTerm(a3, a4), engine.trail);
        } else {
            return engine.fail();
        }
        a5 = new VariableTerm(engine);
        a6 = new VariableTerm(engine);
        a7 = new ListTerm(a5, a6);
        //START inline expansion of $unify(a(1),a(7))
        if (! a1.unify(a7, engine.trail)) {
            return engine.fail();
        }
        //END inline expansion
        return new PRED_$dummy_0_random_helpers$002Epro_10(new VariableTerm(engine), a4, new VariableTerm(engine), new VariableTerm(engine), new VariableTerm(engine), a3, new VariableTerm(engine), a5, a6, a1, cont);
    }
}
