package prolog;

import jp.ac.kobe_u.cs.prolog.lang.*;
import jp.ac.kobe_u.cs.prolog.builtin.*;
/*
 This file is generated by Prolog Cafe.
 PLEASE DO NOT EDIT!
*/
/**
 <code>last/2</code> defined in plcafe_defs.pro<br>
 @author Mutsunori Banbara (banbara@kobe-u.ac.jp)
 @author Naoyuki Tamura (tamura@kobe-u.ac.jp)
 @version 1.0
*/
public class PRED_last_2 extends Predicate {
    static SymbolTerm s1 = SymbolTerm.makeSymbol("[]");
    static Predicate _last_2_top = new PRED_last_2_top();
    static Predicate _fail_0 = new PRED_fail_0();
    static Predicate _last_2_var = new PRED_last_2_var();
    static Predicate _last_2_var_1 = new PRED_last_2_var_1();
    static Predicate _last_2_1 = new PRED_last_2_1();
    static Predicate _last_2_2 = new PRED_last_2_2();

    public Term arg1, arg2;

    public PRED_last_2(Term a1, Term a2, Predicate cont) {
        arg1 = a1;
        arg2 = a2;
        this.cont = cont;
    }

    public PRED_last_2(){}

    public void setArgument(Term[] args, Predicate cont) {
        arg1 = args[0];
        arg2 = args[1];
        this.cont = cont;
    }

    public int arity() { return 2; }

    public String toString() {
        return "last(" + arg1 + "," + arg2 + ")";
    }

    public Predicate exec(Prolog engine) {
        engine.aregs[1] = arg1;
        engine.aregs[2] = arg2;
        engine.cont = cont;
        return _last_2_top;
    }
}

class PRED_last_2_top extends PRED_last_2 {
    public Predicate exec(Prolog engine) {
        engine.setB0();
        return engine.switch_on_term(_last_2_var, _fail_0, _fail_0, _fail_0, _fail_0, _last_2_var);
    }
}

class PRED_last_2_var extends PRED_last_2 {
    public Predicate exec(Prolog engine) {
        return engine.jtry(_last_2_1, _last_2_var_1);
    }
}

class PRED_last_2_var_1 extends PRED_last_2 {
    public Predicate exec(Prolog engine) {
        return engine.trust(_last_2_2);
    }
}

class PRED_last_2_1 extends PRED_last_2 {
    public Predicate exec(Prolog engine) {
    // last([A],A):-true
        Term a1, a2, a3;
        Predicate cont;
        a1 = engine.aregs[1];
        a2 = engine.aregs[2];
        cont = engine.cont;
    // last([A],A):-[]
        a1 = a1.dereference();
        if (a1.isList()){
            Term[] args = {((ListTerm)a1).car(), ((ListTerm)a1).cdr()};
            a3 = args[0];
            if (! s1.unify(args[1], engine.trail))
                return engine.fail();
        } else if (a1.isVariable()){
            a3 = new VariableTerm(engine);
            ((VariableTerm) a1).bind(new ListTerm(a3, s1), engine.trail);
        } else {
            return engine.fail();
        }
        if (! a3.unify(a2, engine.trail))
            return engine.fail();
        return cont;
    }
}

class PRED_last_2_2 extends PRED_last_2 {
    public Predicate exec(Prolog engine) {
    // last([A,B|C],D):-last([B|C],D)
        Term a1, a2, a3, a4, a5, a6;
        Predicate cont;
        a1 = engine.aregs[1];
        a2 = engine.aregs[2];
        cont = engine.cont;
    // last([A,B|C],D):-[last([B|C],D)]
        a1 = a1.dereference();
        if (a1.isList()){
            Term[] args = {((ListTerm)a1).car(), ((ListTerm)a1).cdr()};
            a3 = args[1];
        } else if (a1.isVariable()){
            a3 = new VariableTerm(engine);
            ((VariableTerm) a1).bind(new ListTerm(new VariableTerm(engine), a3), engine.trail);
        } else {
            return engine.fail();
        }
        a3 = a3.dereference();
        if (a3.isList()){
            Term[] args = {((ListTerm)a3).car(), ((ListTerm)a3).cdr()};
            a4 = args[0];
            a5 = args[1];
        } else if (a3.isVariable()){
            a4 = new VariableTerm(engine);
            a5 = new VariableTerm(engine);
            ((VariableTerm) a3).bind(new ListTerm(a4, a5), engine.trail);
        } else {
            return engine.fail();
        }
        a6 = new ListTerm(a4, a5);
        engine.aregs[1] = a6;
        engine.aregs[2] = a2;
        engine.cont = cont;
        return _last_2_top;
    }
}
