import jp.ac.kobe_u.cs.prolog.lang.*;
import jp.ac.kobe_u.cs.prolog.builtin.*;
/*
 This file is generated by Prolog Cafe.
 PLEASE DO NOT EDIT!
*/
/**
 <code>map_fn/3</code> defined in functional.pro<br>
 @author Mutsunori Banbara (banbara@kobe-u.ac.jp)
 @author Naoyuki Tamura (tamura@kobe-u.ac.jp)
 @version 1.0
*/
public class PRED_map_fn_3 extends Predicate {
    static SymbolTerm s1 = SymbolTerm.makeSymbol("[]");
    static SymbolTerm s2 = SymbolTerm.makeSymbol("fn", 2);
    static Predicate _fail_0 = new PRED_fail_0();
    static Predicate _map_fn_3_var = new PRED_map_fn_3_var();
    static Predicate _map_fn_3_var_1 = new PRED_map_fn_3_var_1();
    static Predicate _map_fn_3_1 = new PRED_map_fn_3_1();
    static Predicate _map_fn_3_2 = new PRED_map_fn_3_2();

    public Term arg1, arg2, arg3;

    public PRED_map_fn_3(Term a1, Term a2, Term a3, Predicate cont) {
        arg1 = a1;
        arg2 = a2;
        arg3 = a3;
        this.cont = cont;
    }

    public PRED_map_fn_3(){}

    public void setArgument(Term[] args, Predicate cont) {
        arg1 = args[0];
        arg2 = args[1];
        arg3 = args[2];
        this.cont = cont;
    }

    public int arity() { return 3; }

    public String toString() {
        return "map_fn(" + arg1 + "," + arg2 + "," + arg3 + ")";
    }

    public Predicate exec(Prolog engine) {
        engine.aregs[1] = arg1;
        engine.aregs[2] = arg2;
        engine.aregs[3] = arg3;
        engine.cont = cont;
        engine.setB0();
        return engine.switch_on_term(_map_fn_3_var, _fail_0, _fail_0, _map_fn_3_1, _fail_0, _map_fn_3_2);
    }
}

class PRED_map_fn_3_var extends PRED_map_fn_3 {
    public Predicate exec(Prolog engine) {
        return engine.jtry(_map_fn_3_1, _map_fn_3_var_1);
    }
}

class PRED_map_fn_3_var_1 extends PRED_map_fn_3 {
    public Predicate exec(Prolog engine) {
        return engine.trust(_map_fn_3_2);
    }
}

class PRED_map_fn_3_1 extends PRED_map_fn_3 {
    public Predicate exec(Prolog engine) {
    // map_fn([],A,[]):-!
        Term a1, a2, a3;
        Predicate cont;
        a1 = engine.aregs[1];
        a2 = engine.aregs[2];
        a3 = engine.aregs[3];
        cont = engine.cont;
    // map_fn([],A,[]):-['$neck_cut']
        a1 = a1.dereference();
        if (a1.isSymbol()){
            if (! a1.equals(s1))
                return engine.fail();
        } else if (a1.isVariable()){
            ((VariableTerm) a1).bind(s1, engine.trail);
        } else {
            return engine.fail();
        }
        a3 = a3.dereference();
        if (a3.isSymbol()){
            if (! a3.equals(s1))
                return engine.fail();
        } else if (a3.isVariable()){
            ((VariableTerm) a3).bind(s1, engine.trail);
        } else {
            return engine.fail();
        }
        //START inline expansion of $neck_cut
        engine.neckCut();
        //END inline expansion
        return cont;
    }
}

class PRED_map_fn_3_2 extends PRED_map_fn_3 {
    public Predicate exec(Prolog engine) {
    // map_fn([A|B],fn(C,D),[E|F]):-apply_fn(C,D,[A,E]),map_fn(B,fn(C,D),F)
        Term a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12;
        Predicate p1;
        Predicate cont;
        a1 = engine.aregs[1];
        a2 = engine.aregs[2];
        a3 = engine.aregs[3];
        cont = engine.cont;
    // map_fn([A|B],fn(C,D),[E|F]):-[apply_fn(C,D,[A,E]),map_fn(B,fn(C,D),F)]
        a1 = a1.dereference();
        if (a1.isList()){
            Term[] args = {((ListTerm)a1).car(), ((ListTerm)a1).cdr()};
            a4 = args[0];
            a5 = args[1];
        } else if (a1.isVariable()){
            a4 = new VariableTerm(engine);
            a5 = new VariableTerm(engine);
            ((VariableTerm) a1).bind(new ListTerm(a4, a5), engine.trail);
        } else {
            return engine.fail();
        }
        a2 = a2.dereference();
        if (a2.isStructure()){
            if (! s2.equals(((StructureTerm)a2).functor()))
                return engine.fail();
            Term[] args = ((StructureTerm)a2).args();
            a6 = args[0];
            a7 = args[1];
        } else if (a2.isVariable()){
            a6 = new VariableTerm(engine);
            a7 = new VariableTerm(engine);
            Term[] args = {a6, a7};
            ((VariableTerm) a2).bind(new StructureTerm(s2, args), engine.trail);
        } else {
            return engine.fail();
        }
        a3 = a3.dereference();
        if (a3.isList()){
            Term[] args = {((ListTerm)a3).car(), ((ListTerm)a3).cdr()};
            a8 = args[0];
            a9 = args[1];
        } else if (a3.isVariable()){
            a8 = new VariableTerm(engine);
            a9 = new VariableTerm(engine);
            ((VariableTerm) a3).bind(new ListTerm(a8, a9), engine.trail);
        } else {
            return engine.fail();
        }
        a10 = new ListTerm(a8, s1);
        a11 = new ListTerm(a4, a10);
        Term[] y1 = {a6, a7};
        a12 = new StructureTerm(s2, y1);
        p1 = new PRED_map_fn_3(a5, a12, a9, cont);
        return new PRED_apply_fn_3(a6, a7, a11, p1);
    }
}
