package prolog;

import jp.ac.kobe_u.cs.prolog.lang.*;
import jp.ac.kobe_u.cs.prolog.builtin.*;
/*
 This file is generated by Prolog Cafe.
 PLEASE DO NOT EDIT!
*/
/**
 <code>metric_value/3</code> defined in longuet_higgins.pro<br>
 @author Mutsunori Banbara (banbara@kobe-u.ac.jp)
 @author Naoyuki Tamura (tamura@kobe-u.ac.jp)
 @version 1.0
*/
public class PRED_metric_value_3 extends Predicate {
    static IntegerTerm si1 = new IntegerTerm(1);

    public Term arg1, arg2, arg3;

    public PRED_metric_value_3(Term a1, Term a2, Term a3, Predicate cont) {
        arg1 = a1;
        arg2 = a2;
        arg3 = a3;
        this.cont = cont;
    }

    public PRED_metric_value_3(){}

    public void setArgument(Term[] args, Predicate cont) {
        arg1 = args[0];
        arg2 = args[1];
        arg3 = args[2];
        this.cont = cont;
    }

    public int arity() { return 3; }

    public String toString() {
        return "metric_value(" + arg1 + "," + arg2 + "," + arg3 + ")";
    }

    public Predicate exec(Prolog engine) {
    // metric_value(A,B,C):-D is A-B,factors_of_two(D,E),factors_of_two(A,F),C is F-E+1
        engine.setB0();
        Term a1, a2, a3, a4, a5, a6, a7;
        Predicate p1, p2, p3;
        a1 = arg1;
        a2 = arg2;
        a3 = arg3;
    // metric_value(A,B,C):-['$minus'(A,B,D),factors_of_two(D,E),factors_of_two(A,F),'$minus'(F,E,G),'$plus'(G,1,C)]
        a4 = new VariableTerm(engine);
        //START inline expansion of $minus(a(1),a(2),a(4))
        try {
            if (! a4.unify(Arithmetic.evaluate(a1).subtract(Arithmetic.evaluate(a2)), engine.trail)) {
                return engine.fail();
            }
        } catch (BuiltinException e) {
            e.goal = this;
            throw e;
        }
        //END inline expansion
        a5 = new VariableTerm(engine);
        a6 = new VariableTerm(engine);
        a7 = new VariableTerm(engine);
        p1 = new PRED_$plus_3(a7, si1, a3, cont);
        p2 = new PRED_$minus_3(a6, a5, a7, p1);
        p3 = new PRED_factors_of_two_2(a1, a6, p2);
        return new PRED_factors_of_two_2(a4, a5, p3);
    }
}
