package prolog;

import jp.ac.kobe_u.cs.prolog.lang.*;
import jp.ac.kobe_u.cs.prolog.builtin.*;
/*
 This file is generated by Prolog Cafe.
 PLEASE DO NOT EDIT!
*/
/**
 <code>rand_float/1</code> defined in rule_expander.pro<br>
 @author Mutsunori Banbara (banbara@kobe-u.ac.jp)
 @author Naoyuki Tamura (tamura@kobe-u.ac.jp)
 @version 1.0
*/
public class PRED_rand_float_1 extends Predicate {

    public Term arg1;

    public PRED_rand_float_1(Term a1, Predicate cont) {
        arg1 = a1;
        this.cont = cont;
    }

    public PRED_rand_float_1(){}

    public void setArgument(Term[] args, Predicate cont) {
        arg1 = args[0];
        this.cont = cont;
    }

    public int arity() { return 1; }

    public String toString() {
        return "rand_float(" + arg1 + ")";
    }

    public Predicate exec(Prolog engine) {
    // rand_float(A):-'$dummy_0_rule_expander.pro'(A,B)
        engine.setB0();
        Term a1;
        a1 = arg1;
    // rand_float(A):-['$dummy_0_rule_expander.pro'(A,B)]
        return new PRED_$dummy_0_rule_expander$002Epro_2(a1, new VariableTerm(engine), cont);
    }
}
