package prolog;

import jp.ac.kobe_u.cs.prolog.lang.*;
import jp.ac.kobe_u.cs.prolog.builtin.*;
/*
 This file is generated by Prolog Cafe.
 PLEASE DO NOT EDIT!
*/
/**
 <code>not_containing_nil/1</code> defined in functional.pro<br>
 @author Mutsunori Banbara (banbara@kobe-u.ac.jp)
 @author Naoyuki Tamura (tamura@kobe-u.ac.jp)
 @version 1.0
*/
public class PRED_not_containing_nil_1 extends Predicate {
    static SymbolTerm s1 = SymbolTerm.makeSymbol("[]");

    public Term arg1;

    public PRED_not_containing_nil_1(Term a1, Predicate cont) {
        arg1 = a1;
        this.cont = cont;
    }

    public PRED_not_containing_nil_1(){}

    public void setArgument(Term[] args, Predicate cont) {
        arg1 = args[0];
        this.cont = cont;
    }

    public int arity() { return 1; }

    public String toString() {
        return "not_containing_nil(" + arg1 + ")";
    }

    public Predicate exec(Prolog engine) {
    // not_containing_nil(A):-A=..[B,C],C\=[]
        engine.setB0();
        Term a1, a2, a3, a4;
        Predicate p1;
        a1 = arg1;
    // not_containing_nil(A):-['$univ'(A,[B,C]),'$not_unifiable'(C,[])]
        a2 = new VariableTerm(engine);
        a3 = new ListTerm(a2, s1);
        a4 = new ListTerm(new VariableTerm(engine), a3);
        p1 = new PRED_$not_unifiable_2(a2, s1, cont);
        return new PRED_$univ_2(a1, a4, p1);
    }
}
