import jp.ac.kobe_u.cs.prolog.lang.*;
import jp.ac.kobe_u.cs.prolog.builtin.*;
/*
 This file is generated by Prolog Cafe.
 PLEASE DO NOT EDIT!
*/
/**
 <code>expand_one_level_and_get_attrs/4</code> defined in rule_expander.pro<br>
 @author Mutsunori Banbara (banbara@kobe-u.ac.jp)
 @author Naoyuki Tamura (tamura@kobe-u.ac.jp)
 @version 1.0
*/
public class PRED_expand_one_level_and_get_attrs_4 extends Predicate {
    static SymbolTerm s1 = SymbolTerm.makeSymbol(":", 2);
    static SymbolTerm s2 = SymbolTerm.makeSymbol("user");
    static SymbolTerm s3 = SymbolTerm.makeSymbol("rule", 4);

    public Term arg1, arg2, arg3, arg4;

    public PRED_expand_one_level_and_get_attrs_4(Term a1, Term a2, Term a3, Term a4, Predicate cont) {
        arg1 = a1;
        arg2 = a2;
        arg3 = a3;
        arg4 = a4;
        this.cont = cont;
    }

    public PRED_expand_one_level_and_get_attrs_4(){}

    public void setArgument(Term[] args, Predicate cont) {
        arg1 = args[0];
        arg2 = args[1];
        arg3 = args[2];
        arg4 = args[3];
        this.cont = cont;
    }

    public int arity() { return 4; }

    public String toString() {
        return "expand_one_level_and_get_attrs(" + arg1 + "," + arg2 + "," + arg3 + "," + arg4 + ")";
    }

    public Predicate exec(Prolog engine) {
    // expand_one_level_and_get_attrs(A,B,C,D):-rule(A,B,C,E),E,bottom_up_attr(A,F),dynamic_attr(B,G),append(G,F,D)
        engine.setB0();
        Term a1, a2, a3, a4, a5, a6, a7, a8, a9, a10;
        Predicate p1, p2, p3, p4;
        a1 = arg1;
        a2 = arg2;
        a3 = arg3;
        a4 = arg4;
    // expand_one_level_and_get_attrs(A,B,C,D):-[call(user:rule(A,B,C,E)),call(user:E),bottom_up_attr(A,F),dynamic_attr(B,G),append(G,F,D)]
        a5 = new VariableTerm(engine);
        Term[] y1 = {a1, a2, a3, a5};
        a6 = new StructureTerm(s3, y1);
        Term[] y2 = {s2, a6};
        a7 = new StructureTerm(s1, y2);
        Term[] y3 = {s2, a5};
        a8 = new StructureTerm(s1, y3);
        a9 = new VariableTerm(engine);
        a10 = new VariableTerm(engine);
        p1 = new PRED_append_3(a10, a9, a4, cont);
        p2 = new PRED_dynamic_attr_2(a2, a10, p1);
        p3 = new PRED_bottom_up_attr_2(a1, a9, p2);
        p4 = new PRED_call_1(a8, p3);
        return new PRED_call_1(a7, p4);
    }
}
