import jp.ac.kobe_u.cs.prolog.lang.*;
import jp.ac.kobe_u.cs.prolog.builtin.*;
/*
 This file is generated by Prolog Cafe.
 PLEASE DO NOT EDIT!
*/
/**
 <code>apply_fn/3</code> defined in functional.pro<br>
 @author Mutsunori Banbara (banbara@kobe-u.ac.jp)
 @author Naoyuki Tamura (tamura@kobe-u.ac.jp)
 @version 1.0
*/
public class PRED_apply_fn_3 extends Predicate {
    static SymbolTerm s1 = SymbolTerm.makeSymbol("fn", 2);
    static SymbolTerm s2 = SymbolTerm.makeSymbol(":", 2);
    static SymbolTerm s3 = SymbolTerm.makeSymbol("user");

    public Term arg1, arg2, arg3;

    public PRED_apply_fn_3(Term a1, Term a2, Term a3, Predicate cont) {
        arg1 = a1;
        arg2 = a2;
        arg3 = a3;
        this.cont = cont;
    }

    public PRED_apply_fn_3(){}

    public void setArgument(Term[] args, Predicate cont) {
        arg1 = args[0];
        arg2 = args[1];
        arg3 = args[2];
        this.cont = cont;
    }

    public int arity() { return 3; }

    public String toString() {
        return "apply_fn(" + arg1 + "," + arg2 + "," + arg3 + ")";
    }

    public Predicate exec(Prolog engine) {
    // apply_fn(A,B,C):-copy_term(fn(A,B),D),D=fn(C,E),call(E)
        engine.setB0();
        Term a1, a2, a3, a4, a5, a6, a7, a8;
        a1 = arg1;
        a2 = arg2;
        a3 = arg3;
    // apply_fn(A,B,C):-[copy_term(fn(A,B),D),'$unify'(D,fn(C,E)),call(user:E)]
        Term[] y1 = {a1, a2};
        a4 = new StructureTerm(s1, y1);
        a5 = new VariableTerm(engine);
        //START inline expansion of copy_term(a(4),a(5))
        a4 = a4.dereference();
        if (! a5.unify(engine.copy(a4), engine.trail)) {
            return engine.fail();
        }
        //END inline expansion
        a6 = new VariableTerm(engine);
        Term[] y2 = {a3, a6};
        a7 = new StructureTerm(s1, y2);
        //START inline expansion of $unify(a(5),a(7))
        if (! a5.unify(a7, engine.trail)) {
            return engine.fail();
        }
        //END inline expansion
        Term[] y3 = {s3, a6};
        a8 = new StructureTerm(s2, y3);
        return new PRED_call_1(a8, cont);
    }
}
