/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewBrickDialog.java
 *
 * Created on Jun 29, 2011, 11:49:31 AM
 */
package imp.roadmap;

import imp.brickdictionary.*;
import java.awt.Image;
/**
 *
 * @author ImproVisor
 */
public class NewBrickDialog extends javax.swing.JDialog {

private int previewPanelWidth = 800;
private int previewPanelHeight = 500;

private PreviewPanel previewPanel;
     
    RoadMapFrame view;
    
    /** Creates new form NewBrickDialog */
    public NewBrickDialog(RoadMapFrame view) {
        
        // This seems awkward to me.
        super((java.awt.Frame)null, true);
        initComponents();
        
        if( previewPanel == null )
        {
        previewPanel = new PreviewPanel(view);
        }
        
        this.view = view;
        
        // This is a hack to work around the problem that 
        // the previewPanel is not affixed to the JScrollPane at its 
        // construction time.
        
        newBrickScrollPane.removeAll();
        previewPanel.setBounds(0, 0, previewPanelWidth, previewPanelHeight);
        setBounds(0, 0, previewPanelWidth, previewPanelHeight);
        newBrickScrollPane.add(previewPanel);
    }
    
    public void activate(Brick brick)
    {
        setBrick(brick);
        setVisible(true);
    }

    public void changeName()
    {
        previewPanel.setBrickName(nameField.getText());
    }

    public void setBrick(Brick brick)
    { 
        nameField.setText(brick.getName());
        
        previewPanel.setBrick(brick);
        previewPanel.draw();
    }
    
    public Brick getBrick()
    {
        
        return previewPanel.returnBrick();
    }
    
    public void setBuffer(Image buffer)
    {
        previewPanel.setBuffer(buffer);
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        nameLabel = new javax.swing.JLabel();
        keyLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        keySpinner = new javax.swing.JSpinner();
        acceptButton = new javax.swing.JButton();
        newBrickScrollPane = new javax.swing.JScrollPane(previewPanel);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                NewBrickDialog.this.windowActivated(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        nameLabel.setName("nameLabel"); // NOI18N
        getContentPane().add(nameLabel, new java.awt.GridBagConstraints());

        keyLabel.setName("keyLabel"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        getContentPane().add(keyLabel, gridBagConstraints);

        nameField.setName("nameField"); // NOI18N
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.9;
        getContentPane().add(nameField, gridBagConstraints);

        keySpinner.setName("keySpinner"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(keySpinner, gridBagConstraints);

//        acceptButton.setText(resourceMap.getString("acceptButton.text")); // NOI18N
        acceptButton.setName("acceptButton"); // NOI18N
        acceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptButtonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(acceptButton, gridBagConstraints);

        newBrickScrollPane.setDoubleBuffered(true);
        newBrickScrollPane.setMinimumSize(new java.awt.Dimension(800, 200));
        newBrickScrollPane.setName("newBrickScrollPane"); // NOI18N
        newBrickScrollPane.setPreferredSize(new java.awt.Dimension(800, 600));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(newBrickScrollPane, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        changeName();
}//GEN-LAST:event_nameFieldActionPerformed

    private void windowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowActivated
        System.out.println("New Brick Dialog activated");
        previewPanel.draw();
    }//GEN-LAST:event_windowActivated

    private void acceptButtonPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptButtonPressed
        setVisible(false);
    }//GEN-LAST:event_acceptButtonPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButton;
    private javax.swing.JLabel keyLabel;
    private javax.swing.JSpinner keySpinner;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JScrollPane newBrickScrollPane;
    // End of variables declaration//GEN-END:variables
}
