/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AttributeFrame.java
 *
 * Created on Jul 9, 2010, 10:23:48 AM
 */

package imp.gui;

import java.awt.*;
import javax.swing.BorderFactory;



/**
 * Frame for testing the adjustable complexity attribute window, probably not to be used later.
 * @author Julia Botev
 */
public class ComplexityFrame extends javax.swing.JFrame {

    public static final int WINDOW_WIDTH = 1000;
    public static final int WINDOW_HEIGHT = 700;
    public static final int GRAPH_WIDTH = 300;
    public static final int GRAPH_HEIGHT = 200;

    /** Creates new form AttributeFrame */
    public ComplexityFrame() {
        initComponents();
        //jFrame1.setSize(WINDOW_WIDTH, WINDOW_HEIGHT);

        Image image1 = complexityGraphPanel.createImage(GRAPH_WIDTH, GRAPH_HEIGHT);
        ((ComplexityPanel) complexityGraphPanel).setBuffer(image1);
        ((ComplexityPanel) complexityGraphPanel).setGraphics();
        ((ComplexityPanel) complexityGraphPanel).setColor(Color.ORANGE);

        Image image2 = densityPanel.createImage(GRAPH_WIDTH, GRAPH_HEIGHT);
        ((ComplexityPanel) densityPanel).setBuffer(image2);
        ((ComplexityPanel) densityPanel).setGraphics();
        ((ComplexityPanel) densityPanel).setColor(Color.CYAN);

        Image image3 = jPanel1.createImage(GRAPH_WIDTH, GRAPH_HEIGHT);
        ((ComplexityPanel) jPanel1).setBuffer(image3);
        ((ComplexityPanel) jPanel1).setGraphics();
        ((ComplexityPanel) jPanel1).setColor(Color.PINK);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        complexityGraphPanel = new ComplexityPanel(GRAPH_WIDTH, GRAPH_HEIGHT, 2, 40);
        attributeScrollPane = new javax.swing.JScrollPane();
        densityPanel = new ComplexityPanel(GRAPH_WIDTH, GRAPH_HEIGHT, 2, 40);
        jPanel1 = new ComplexityPanel(GRAPH_WIDTH, GRAPH_HEIGHT, 2, 40);
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        complexityGraphPanel.setBackground(new java.awt.Color(255, 255, 255));
        complexityGraphPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Complexity Curve", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 13))); // NOI18N

        complexityGraphPanel.setPreferredSize(new java.awt.Dimension(300, 200));

        complexityGraphPanel.setLayout(new java.awt.GridBagLayout());
        complexityGraphPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseEventHandler(evt);
            }
        });
        complexityGraphPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                mouseEventHandler(evt);
            }
        });

        javax.swing.GroupLayout complexityGraphPanelLayout = new javax.swing.GroupLayout(complexityGraphPanel);
        complexityGraphPanel.setLayout(complexityGraphPanelLayout);
        complexityGraphPanelLayout.setHorizontalGroup(
            complexityGraphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        complexityGraphPanelLayout.setVerticalGroup(
            complexityGraphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(complexityGraphPanel, gridBagConstraints);
        //gridBagConstraints.gridx = 0;
        //gridBagConstraints.gridy = 1;
        //gridBagConstraints.gridwidth = 2;
        //gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        //gridBagConstraints.anchor = java.awt.GridBagConstraints.CENTER;
        //gridBagConstraints.weightx = 1.0;
        //gridBagConstraints.weighty = 0.5;
        //complexityGraphPanel.add(complexityPanel, gridBagConstraints);

        attributeScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        attributeScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        densityPanel.setBackground(new java.awt.Color(255, 255, 255));
        densityPanel.setPreferredSize(new java.awt.Dimension(300, 200));
        densityPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseEventHandler(evt);
            }
        });
        densityPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                mouseEventHandler(evt);
            }
        });

        javax.swing.GroupLayout densityPanelLayout = new javax.swing.GroupLayout(densityPanel);
        densityPanel.setLayout(densityPanelLayout);
        densityPanelLayout.setHorizontalGroup(
            densityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 382, Short.MAX_VALUE)
        );
        densityPanelLayout.setVerticalGroup(
            densityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );

        attributeScrollPane.setViewportView(densityPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(attributeScrollPane, gridBagConstraints);

        complexityGraphPanel.setBackground(new java.awt.Color(255, 255, 255));
        complexityGraphPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Complexity Curve", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 13))); // NOI18N
        complexityGraphPanel.setPreferredSize(new java.awt.Dimension(300, 200));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseEventHandler(evt);
            }
        });
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                mouseEventHandler(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel1, gridBagConstraints);

        jPanel2.setBorder(BorderFactory.createLineBorder(Color.black));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.25;
        gridBagConstraints.weighty = 0.25;
        getContentPane().add(jPanel2, gridBagConstraints);

        jPanel3.setBorder(BorderFactory.createLineBorder(Color.black));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.25;
        gridBagConstraints.weighty = 0.25;
        getContentPane().add(jPanel3, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mouseEventHandler(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseEventHandler
        ((ComplexityPanel)evt.getSource()).mouseHandler(evt);
    }//GEN-LAST:event_mouseEventHandler

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComplexityFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane attributeScrollPane;
    private javax.swing.JPanel complexityGraphPanel;
    private javax.swing.JPanel densityPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
