/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ComplexityWindow.java
 *
 * Created on Jul 15, 2010, 2:37:13 PM
 */

package imp.gui;

import java.awt.*;

/**
 * The adjustable complexity attribute window.
 * @author Julia Botev
 */
public class ComplexityWindow extends javax.swing.JPanel {
;
    public static final int GRAPH_WIDTH = 300;
    public static final int GRAPH_HEIGHT = 100;


    /** Creates new form ComplexityWindow */
    public ComplexityWindow() {
        initComponents();
    }

    public void initImageBuffers() {
        Image image1 = complexityGraphPanel.createImage(GRAPH_WIDTH, GRAPH_HEIGHT);
        ((ComplexityPanel) complexityGraphPanel).setBuffer(image1);
        ((ComplexityPanel) complexityGraphPanel).setGraphics();
        ((ComplexityPanel) complexityGraphPanel).setColor(Color.ORANGE);

        Image image2 = densityPanel.createImage(GRAPH_WIDTH, GRAPH_HEIGHT);
        ((ComplexityPanel) densityPanel).setBuffer(image2);
        ((ComplexityPanel) densityPanel).setGraphics();
        ((ComplexityPanel) densityPanel).setColor(Color.CYAN);

        Image image3 = varietyPanel.createImage(GRAPH_WIDTH, GRAPH_HEIGHT);
        ((ComplexityPanel) varietyPanel).setBuffer(image3);
        ((ComplexityPanel) varietyPanel).setGraphics();
        ((ComplexityPanel) varietyPanel).setColor(Color.PINK);

        Image image4 = syncopationPanel.createImage(GRAPH_WIDTH, GRAPH_HEIGHT);
        ((ComplexityPanel) syncopationPanel).setBuffer(image4);
        ((ComplexityPanel) syncopationPanel).setGraphics();
        ((ComplexityPanel) syncopationPanel).setColor(Color.GREEN);
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        globalViewPanel = new javax.swing.JPanel();
        complexityGraphPanel = new ComplexityPanel(GRAPH_WIDTH, GRAPH_HEIGHT, 2, 40);
        globalControlPanel = new javax.swing.JPanel();
        specificAttributePanel = new javax.swing.JPanel();
        attributeScrollPane = new javax.swing.JScrollPane();
        attributePanel = new javax.swing.JPanel();
        densityPanel = new ComplexityPanel(GRAPH_WIDTH, GRAPH_HEIGHT, 2, 40);
        varietyPanel = new ComplexityPanel(GRAPH_WIDTH, GRAPH_HEIGHT, 2, 40);
        syncopationPanel = new ComplexityPanel(GRAPH_WIDTH, GRAPH_HEIGHT, 2, 40);
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setLayout(new java.awt.GridBagLayout());

        globalViewPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Global Complexity View"));
        globalViewPanel.setAlignmentX(0.0F);
        globalViewPanel.setAlignmentY(0.0F);
        globalViewPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        globalViewPanel.setPreferredSize(new java.awt.Dimension(830, 120));
        globalViewPanel.setLayout(new java.awt.GridBagLayout());
        globalViewPanel.setSize(globalViewPanel.getPreferredSize());

        complexityGraphPanel.setBackground(new java.awt.Color(255, 255, 255));
        complexityGraphPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        complexityGraphPanel.setMaximumSize(new java.awt.Dimension(300, 100));
        complexityGraphPanel.setMinimumSize(new java.awt.Dimension(300, 100));
        complexityGraphPanel.setPreferredSize(new java.awt.Dimension(300, 100));
        complexityGraphPanel.setLayout(new java.awt.GridBagLayout());
        complexityGraphPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseEventHandler(evt);
            }
        });
        complexityGraphPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                mouseEventHandler(evt);
            }
        });

        javax.swing.GroupLayout complexityGraphPanelLayout = new javax.swing.GroupLayout(complexityGraphPanel);
        complexityGraphPanel.setLayout(complexityGraphPanelLayout);
        complexityGraphPanelLayout.setHorizontalGroup(
            complexityGraphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 425, Short.MAX_VALUE)
        );
        complexityGraphPanelLayout.setVerticalGroup(
            complexityGraphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.25;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        globalViewPanel.add(complexityGraphPanel, gridBagConstraints);
        //gridBagConstraints.gridx = 0;
        //gridBagConstraints.gridy = 1;
        //gridBagConstraints.gridwidth = 2;
        //gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        //gridBagConstraints.anchor = java.awt.GridBagConstraints.CENTER;
        //gridBagConstraints.weightx = 1.0;
        //gridBagConstraints.weighty = 0.5;
        //complexityGraphPanel.add(complexityPanel, gridBagConstraints);

        globalControlPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        globalControlPanel.setMaximumSize(new java.awt.Dimension(32767, 100));
        globalControlPanel.setMinimumSize(new java.awt.Dimension(0, 100));
        globalControlPanel.setPreferredSize(new java.awt.Dimension(530, 100));

        javax.swing.GroupLayout globalControlPanelLayout = new javax.swing.GroupLayout(globalControlPanel);
        globalControlPanel.setLayout(globalControlPanelLayout);
        globalControlPanelLayout.setHorizontalGroup(
            globalControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        globalControlPanelLayout.setVerticalGroup(
            globalControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.75;
        gridBagConstraints.weighty = 0.5;
        globalViewPanel.add(globalControlPanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.25;
        add(globalViewPanel, gridBagConstraints);

        specificAttributePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Adjust Individual Attributes"));
        specificAttributePanel.setAlignmentX(0.0F);
        specificAttributePanel.setPreferredSize(new java.awt.Dimension(830, 400));
        specificAttributePanel.setLayout(new java.awt.GridBagLayout());

        attributeScrollPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        attributeScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        attributeScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        attributeScrollPane.setMinimumSize(new java.awt.Dimension(0, 0));

        attributePanel.setBackground(new java.awt.Color(255, 255, 255));
        attributePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        attributePanel.setAlignmentX(0.0F);
        attributePanel.setAlignmentY(0.0F);
        attributePanel.setPreferredSize(new java.awt.Dimension(830, 830));
        attributePanel.setLayout(new java.awt.GridBagLayout());

        densityPanel.setBackground(new java.awt.Color(255, 255, 255));
        densityPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        densityPanel.setAlignmentX(0.0F);
        densityPanel.setAlignmentY(0.0F);
        densityPanel.setMaximumSize(new java.awt.Dimension(300, 100));
        densityPanel.setMinimumSize(new java.awt.Dimension(300, 100));
        densityPanel.setPreferredSize(new java.awt.Dimension(300, 100));
        densityPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseEventHandler(evt);
            }
        });
        densityPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                mouseEventHandler(evt);
            }
        });

        javax.swing.GroupLayout densityPanelLayout = new javax.swing.GroupLayout(densityPanel);
        densityPanel.setLayout(densityPanelLayout);
        densityPanelLayout.setHorizontalGroup(
            densityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );
        densityPanelLayout.setVerticalGroup(
            densityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.33;
        gridBagConstraints.weighty = 0.33;
        attributePanel.add(densityPanel, gridBagConstraints);

        varietyPanel.setBackground(new java.awt.Color(255, 255, 255));
        varietyPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        varietyPanel.setAlignmentX(0.0F);
        varietyPanel.setAlignmentY(0.0F);
        varietyPanel.setMaximumSize(new java.awt.Dimension(300, 100));
        varietyPanel.setMinimumSize(new java.awt.Dimension(300, 100));
        varietyPanel.setPreferredSize(new java.awt.Dimension(300, 100));
        varietyPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseEventHandler(evt);
            }
        });
        varietyPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                mouseEventHandler(evt);
            }
        });

        javax.swing.GroupLayout varietyPanelLayout = new javax.swing.GroupLayout(varietyPanel);
        varietyPanel.setLayout(varietyPanelLayout);
        varietyPanelLayout.setHorizontalGroup(
            varietyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );
        varietyPanelLayout.setVerticalGroup(
            varietyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.33;
        gridBagConstraints.weighty = 0.33;
        attributePanel.add(varietyPanel, gridBagConstraints);

        syncopationPanel.setBackground(new java.awt.Color(255, 255, 255));
        syncopationPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        syncopationPanel.setAlignmentX(0.0F);
        syncopationPanel.setAlignmentY(0.0F);
        syncopationPanel.setMaximumSize(new java.awt.Dimension(300, 100));
        syncopationPanel.setMinimumSize(new java.awt.Dimension(300, 100));
        syncopationPanel.setPreferredSize(new java.awt.Dimension(300, 100));
        syncopationPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseEventHandler(evt);
            }
        });
        syncopationPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                mouseEventHandler(evt);
            }
        });

        javax.swing.GroupLayout syncopationPanelLayout = new javax.swing.GroupLayout(syncopationPanel);
        syncopationPanel.setLayout(syncopationPanelLayout);
        syncopationPanelLayout.setHorizontalGroup(
            syncopationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );
        syncopationPanelLayout.setVerticalGroup(
            syncopationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.33;
        gridBagConstraints.weighty = 0.33;
        attributePanel.add(syncopationPanel, gridBagConstraints);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(530, 100));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.66;
        gridBagConstraints.weighty = 0.33;
        attributePanel.add(jPanel1, gridBagConstraints);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setPreferredSize(new java.awt.Dimension(530, 100));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.66;
        gridBagConstraints.weighty = 0.33;
        attributePanel.add(jPanel2, gridBagConstraints);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setPreferredSize(new java.awt.Dimension(530, 100));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.66;
        gridBagConstraints.weighty = 0.33;
        attributePanel.add(jPanel3, gridBagConstraints);

        attributeScrollPane.setViewportView(attributePanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 25;
        gridBagConstraints.gridheight = 15;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = -476;
        gridBagConstraints.ipady = -300;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        specificAttributePanel.add(attributeScrollPane, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.75;
        add(specificAttributePanel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 350;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        add(specificAttributePanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void mouseEventHandler(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseEventHandler
        ((ComplexityPanel)evt.getSource()).mouseHandler(evt);
    }//GEN-LAST:event_mouseEventHandler


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel attributePanel;
    private javax.swing.JScrollPane attributeScrollPane;
    private javax.swing.JPanel complexityGraphPanel;
    private javax.swing.JPanel densityPanel;
    private javax.swing.JPanel globalControlPanel;
    private javax.swing.JPanel globalViewPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel specificAttributePanel;
    private javax.swing.JPanel syncopationPanel;
    private javax.swing.JPanel varietyPanel;
    // End of variables declaration//GEN-END:variables

}
